# Generated by Django 5.2.13 on 2026-04-29 17:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128, unique=True)),
                ('rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'contracts_compliancemetric',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('risk', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('risk_reason', models.TextField(blank=True)),
                ('clearance_required', models.PositiveSmallIntegerField(choices=[(0, 'unclassified'), (1, 'confidential'), (2, 'secret'), (3, 'top_secret')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contracts_contract',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('contractor_performance_score', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3)),
            ],
            options={
                'db_table': 'contracts_organizationkpi',
            },
        ),
        migrations.CreateModel(
            name='SpendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('period', models.CharField(max_length=16)),
                ('obligated_usd', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'contracts_spendsnapshot',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContractAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_ref', models.CharField(db_index=True, help_text='contract_id at time of event (row may be deleted).', max_length=32)),
                ('contract_pk', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('clearance_required', models.PositiveSmallIntegerField(choices=[(0, 'unclassified'), (1, 'confidential'), (2, 'secret'), (3, 'top_secret')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='contracts.contract')),
            ],
            options={
                'db_table': 'contracts_deadline',
                'ordering': ['due_date'],
            },
        ),
    ]
